### ISSUE TITLE
Allow Branch

### ISSUE THREAD

**Issue by the0bone** [FYSETC/FYSETC-BIG_DIPPER#2]
While I can not create a branch from the Big Dipper, I created a Fork to include my CAD data.
https://github.com/the0bone/FYSETC-BIG_DIPPER/tree/main/CAD

**Comment by GerogeFu** [comment]
Do you mind if i copy them to our github?

**Comment by the0bone** [comment]
> 

Sure you can.
But if you add me as contributor to the project, I can open a branch instead of a fork and have the data there and you can commit them to the main branch (yours) if you want. Thats the way how github is working and thats way more efficient.
Also because I'm adding more content while I rebuild my IDEX printer with that board now.
So also a PIN out plan will be there shortly.

**Comment by GerogeFu** [comment]
You have write access to the repo now.
